proj4 : proj4.tex
	pdflatex proj4
	bibtex proj4
	pdflatex proj4
	pdflatex proj4
#	xpdf proj4.pdf

mac : proj4.tex
	pdflatex proj4
	bibtex proj4
	pdflatex proj4
	pdflatex proj4
#	open proj4.pdf

ubuntu : proj4.tex
	pdflatex proj4
	bibtex proj4
	pdflatex proj4
	pdflatex proj4
	gnome-open proj4.pdf

tits : proj4.tex
	pdflatex proj4
	bibtex proj4
	pdflatex proj4
	pdflatex proj4
	xpdf proj4.pdf
